### ISSUE TITLE
PSI normalization

### ISSUE THREAD

**Issue by Dongmeng-wang** [comprna/SUPPA#157]
Hello,

I'm trying to run the differential splicing analyses on RI with the mixed-effect linear model. Do I need to normalize the PSI of RI before feeding them into the model? If so, which strategy of normalization do you recommend? Many thanks for your help.

All the best,
Meng

**Comment by EduEyras** [comment]
Hi Meng,

The PSI is already a normalised value

It is comparable across samples and conditions

However PSI values are usually not normally distributed, which may be a
necessary assumption of some of the models you want to apply

Some people use the logit transformation to operate with the values. If PSI
= P (a value between 0 and 1), then

logit (P) = log (P / (1-P))

Otherwise, working with PSIs should be fine

I hope this helps

E.

**Comment by Dongmeng-wang** [comment]
Thank you so much! I'll try it out. 

Merry Christmas.

Meng

**Comment by Dongmeng-wang** [comment]
Hello. You mentioned the PSI is already a normalised value. May I know how you normalised it? Like quantile normalise within samples? Because I tried to quantile normalise PSI within samples and then found the normalised data is really similar to the original data. So I was wondering if I still need to quantile normalise it myself. Thank you so much for your help.

All the best,
Meng

**Comment by EduEyras** [comment]
Hi,
no need to perform quantile normalisation of PSI values.
PSI represents a proportion: the proportion of RNA abundance that explain the usage of that exon or event type.  It relies on TPM values. These are normalised values as well. However, their distribution may differ between samples. It is worthwhile checking the TPM value distributions and whether it is necessary to perform a TPM normalisation.
