### ISSUE TITLE
Clarification on Interpretation of PSI Values Approaching 1 or 0, and Determining Alternative Splicing.

### ISSUE THREAD

**Issue by qingwangchen** [comprna/SUPPA#167]
Hello Eduardo,

I hope this message finds you well. I have been using PSI values for alternative splicing analysis and have a couple of questions regarding situations where PSI values approach 1 or 0. I would greatly appreciate your insights on these matters.

**Interpretation of PSI Values Approaching 1**: Could you kindly confirm if my understanding is correct that when PSI values approach 1, it indicates constitutive exons that are included in all transcripts and never removed from expressed isoforms, which means very little alternative splicing occurs? Does this suggest that the presence of this exon in transcripts is consistent and stable?

**Interpretation of PSI Values Approaching 0**: If I understand correctly, when PSI values approach 0, it implies that the exon is mostly excluded from transcripts in the majority of cases, indicating a higher likelihood of alternative splicing. In such cases, is it accurate to say that the presence of the exon in transcripts is unstable and potentially subject to regulation?

However, I noticed that the ENCODE consortium's work (https://www.biorxiv.org/content/10.1101/2023.05.15.540865v1.full), where SUPPA2 quantification has been employed. They've used a threshold of 0.25 < PSI < 0.75 to select certain genes for further analysis. Does this suggest that when working with PSI values, it's crucial to be mindful of choosing appropriate threshold values to filter out potentially "unreliable" alternative splicing events?

Original sentence:
We selected genes with at least one local AF or AL event, applying a threshold of 0.25 < PSI < 0.75. 

Additionally, I would like to inquire whether the existence of a PSI value alone indicates the occurrence of alternative splicing, or if there are other factors that need to be considered to confidently determine the presence of alternative splicing events.

Thank you very much for your time and assistance. I am looking forward to your valuable insights.

Best regards,
Qingwang Chen

**Comment by EduEyras** [comment]
Closing this issue. It was answered through an email exchange.

**Comment by nicodemus88** [comment]
@EduEyras I have roughly the same question regarding the interpretation of PSI. Is it possible to put the answer here?

**Comment by EduEyras** [comment]
Dear Nicodemus88,

Yes, no problem. I'm sure that Qingwang wouldn't mind me reproducing the answer here, as these are quite general questions and possibly a broadly useful discussion:

_Interpretation of PSI Values Approaching 1: Could you kindly confirm if my understanding is correct that when PSI values approach 1, it indicates constitutive exons that are included in all transcripts and never removed from expressed isoforms, which means very little alternative splicing occurs? Does this suggest that the presence of this exon in transcripts is consistent and stable?_

That’s right, PSI ~ 1 means that practically all transcripts from that gene express that event.
 
_Interpretation of PSI Values Approaching 0: If I understand correctly, when PSI values approach 0, it implies that the exon is mostly excluded from transcripts in the majority of cases, indicating a higher likelihood of alternative splicing. In such cases, is it accurate to say that the presence of the exon in transcripts is unstable and potentially subject to regulation?_

PSI~0 means that this exon or event is almost never included in the transcripts from that gene.
 
Now, both these cases would indicate that from the two possible splicing variants, only one is expressed.
So there is no alternative splicing in that condition.
 
You could talk about alternative splicing when two or more isoforms are expressed in one condition (hence 0 < PSI < 1 ) or when you care comparing two conditions and the PSI valiues change, e.g. one condition with PSI ~ 1, but in a different condition the exon PSI is ~0, then you do have alternative splicing.
 
It is not necessarily unstable, but the general hypothesis is that it is regulated by some mechanism dependent of the conditions that you’re looking at. Sometimes it is possible it has to do with efficiency of the splice-site detection.
 
_However, I noticed that the ENCODE consortium's work ([https://www.biorxiv.org/content/10.1101/2023.05.15.540865v1.full](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.biorxiv.org%2Fcontent%2F10.1101%2F2023.05.15.540865v1.full&data=05%7C01%7Ceduardo.eyras%40anu.edu.au%7Ca62c76e2de2d48bccd7008db9a71720f%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638273584278342335%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cSGAx61mw6vOG94I3wfBOVHV8iIQakVviR%2B%2FfiwkIyg%3D&reserved=0)), where SUPPA2 quantification has been employed. They've used a threshold of 0.25 < PSI < 0.75 to select certain genes for further analysis. Does this suggest that when working with PSI values, it's crucial to be mindful of choosing appropriate threshold values to filter out potentially "unreliable" alternative splicing events?_

_Original sentence:
We selected genes with at least one local AF or AL event, applying a threshold of 0.25 < PSI < 0.75_

My understanding of what they did is the following. They want to identify cases where the gene produces more than one transcript isoform. In terms of events, this means that the PSI cannot be 1 (or zero). With 0.25 < PSI < 0.75 they make sure to select cases where there are two isoforms being expressed. They are looking at one condition, so perhaps that’s why they do it like, rather than looking at “differential splicing”.
 
_Additionally, I would like to inquire whether the existence of a PSI value alone indicates the occurrence of alternative splicing, or if there are other factors that need to be considered to confidently determine the presence of alternative splicing events._

This depends on whether you’re looking at one single condition or comparing two conditions, as described above.
 
_I've understood that, particularly when comparing diverse conditions such as disease and normal samples, changes in PSI values (Δ PSI) can serve as indicators for the presence of specific types of alternative splicing in disease contexts. However, a question arises when considering scenarios where solely disease samples are available, constituting a single condition without corresponding control samples. In such instances, can alternative splicing be accurately ascertained solely based on PSI values? If so, would it be advisable to establish a definitive PSI value threshold to confidently discern its occurrence? I am eager to gain your insights and expertise on this matter._

We had this situation once (see e.g. https://pubmed.ncbi.nlm.nih.gov/34529669/)
 
In this case, we used PSI values from normal tissues as reference.
 
We reasoned that a tumor-specific splicing will be different from the normal patterns.
 
In your case it could be different, but a similar approach might be possible.
 
If you do not know what “normal” is, then it is difficult to assess what is disease-specific.
 
I guess you could look for aberrant splice-sites (not in the annotation),
Or look for PSIs that are between 0 and 1 (as in the Gencode paper) to look for genes that produce multiple isoforms, but this might also reflect the cell composition, depending on your data.
 
E.

**Comment by nicodemus88** [comment]
@EduEyras Thank you very much for the reply. It is indeed very helpful!
