### ISSUE TITLE
-v b and s ,for iso-seq which is best ?

### ISSUE THREAD

**Issue by wuxunboge** [comprna/SUPPA#26]

**Comment by EduEyras** [comment]
Hi,
I gather you are asking whether using fixed or variable boundaries to define AS events from an annotation built from iso-seq (pacbio) sequences. Is that right?

Iso-seq does not have as many errors as other methods, so splice sites are probably trustable. On the other hand, many intros have very similar sequences around both ends, so I reckon there will some variation. 

I would run with either option and compare results. If the number of events is very different I would perhaps use the variable boundary.

Otherwise it would be fine with fixed biundaries.

This also may depend on your species. Arabidopsis has many overlapping events. You could perhaps try with a small variation first (5-10 nt)

I hope this helps

E

Dr. Eyras
ICREA Research Professor
Universitat Pompeu Fabra
Barcelona
Spain

**Comment by wuxunboge** [comment]
Thank you !
