### ISSUE TITLE
Transcript expression file

### ISSUE THREAD

**Issue by selffi** [comprna/SUPPA#7]
Dear team

I am  analysing AS events in _Arabidopsis thaliana_ using SUPPA. This is the first time I am working with RNA Seq data.  I predicted AS_events using _generateEvents_ option. For calculating PSI, it requires Transcript expression file. But I do not know from where I can get the Transcript expression file for my sample? Can anyone help me in this issue? Thank you in advance

**Comment by JLTrincado** [comment]
Hi selfii,

sorry for the delay. SUPPA uses TPM values for obtaining the PSI changes in the events. There are several methods that allowed you to obtain this from your RNA-seq reads. We strongly recommend using Salmon (https://combine-lab.github.io/salmon/), because is one of the fastest methods for quantification without compromising accuracy and it also offers some other interesting options like GC bias correction or bootstrapping among others.

We have a short tutorial in the wiki (https://github.com/comprna/SUPPA/wiki) if you need help at the time of running the quantification on your samples.

Thanks a lot for your interest in SUPPA!!

**Comment by selffi** [comment]
Thank you for the reply. I'll try it out
